name: ace592
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - bokeh=2.2.3
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.3
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.0
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cryptography=3.1.1
  - curl=7.67.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2020.12.0
  - dask-core=2020.12.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - distributed=2020.12.0
  - econtools=0.3.2
  - entrypoints=0.3
  - expat=2.2.10
  - fiona=1.8.13.post1
  - freetype=2.10.4
  - freexl=1.0.5
  - fsspec=0.8.3
  - gdal=3.0.2
  - geopandas=0.8.1
  - geos=3.8.0
  - geotiff=1.5.1
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.1
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - kealib=1.4.7
  - kiwisolver=1.2.0
  - krb5=1.16.4
  - libboost=1.67.0
  - libcurl=7.67.0
  - libgdal=3.0.2
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libpq=11.2
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libxml2=2.9.10
  - locket=0.2.0
  - lz4-c=1.8.1.2
  - mapclassify=2.3.0
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - msgpack-python=1.0.1
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nest-asyncio=1.4.1
  - networkx=2.5
  - nltk=3.5
  - notebook=6.1.4
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1i
  - overpy=0.4
  - packaging=20.4
  - pandas=1.1.3
  - pandoc=2.11
  - pandocfilters=1.4.2
  - parso=0.7.0
  - partd=1.1.0
  - pcre=8.44
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.2.4
  - plotly=4.12.0
  - postgresql=11.2
  - proj=6.2.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - psutil=5.7.2
  - pycparser=2.20
  - pycrs=1.0.2
  - pygments=2.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - rasterio=1.1.1
  - rasterstats=0.14.0
  - regex=2020.11.13
  - requests=2.24.0
  - retrying=1.3.3
  - rtree=0.9.4
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - send2trash=1.5.0
  - setuptools=50.3.0
  - shapely=1.7.1
  - simplejson=3.17.2
  - sip=4.19.13
  - six=1.15.0
  - snuggs=1.4.7
  - sortedcontainers=2.3.0
  - sqlite=3.33.0
  - tbb=2018.0.5
  - tblib=1.7.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tiledb=1.6.3
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.0.4
  - tqdm=4.54.1
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - vc=14.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zict=2.0.0
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.3.7